const mongoose = require('mongoose')
const orderSchema = new mongoose.Schema(
    {
        customerId:{
            type: mongoose.Schema.Types.ObjectId,
            ref:"Customer",
            required:true
        },
        outletId:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"Outlet",
            required:true
        },
        items:[
            {
                menuItemId:{
                    type: mongoose.Schema.Types.ObjectId,
                    ref:"MenuItem",
                    required:true
                },
                name:{
                    type:String,
                    required:true,
                    trim:true
                },
                price:{
                    type:Number,
                    required:true,
                    min:0
                },
                quantity:{
                    type:Number,
                    required:true,
                    min:1
                },
                subTotal:{
                    type:Number,
                    required:true,
                    min:0
                }
            }
        ],
        deliveryAddress:{
            fullName:{
                type:String,
                required:true,
                trim:true
            },
            phone:{
                type:String,
                required:true,
                trim:true
            },
            addressLine1:{
                type:String,
                required:true,
                trim:true
            },
            addressLine2:{
                type:String,
                default:"",
                trim:true
            },
            city:{
                type:String,
                required:true,
                trim:true
            },
            state:{
                type:String,
                required:true,
                trim:true
            },
            pincode:{
                type:String,
                required:true,
                trim:true
            }
        },
        subTotal:{
            type:Number,
            required:true,
            min:0
        },
        deliveryFee:{
            type:Number,
            required:true,
            min:0
        },
        tax:{
            type:Number,
            required:true,
            min:0
        },
        discount:{
            type:Number,
            default:0,
            min:0
        },
        totalAmount:{
            type:Number,
            required:true,
            min:0
        },
        paymentMethod:{
            type:String,
            enum:["COD","UPI","CARD","NET_BANKING"],
            required:true
        },
        paymentStatus:{
            type:String,
            enum:["pending","paid","failed","refunded"],
            default:"pending"
        },
        orderStatus:{
            type:String,
            enum:[
                "placed",
                "confirmed",
                "preparing",
                "ready",
                "out_for_delivery",
                "delivered",
                "cancelled"
            ],
            default:"placed"
        }
    },
    {
        timestamps:true
    }
)
module.exports = mongoose.model("Order",orderSchema);