const mongoose = require('mongoose')
const itemSchema = new mongoose.Schema(
    {
        item:{
            type: mongoose.Schema.Types.ObjectId,
            ref:"MenuItem",
            required:true
        },
        name:{
            type:String,
            required:true,
            trim:true
        },
        price:{
            type:Number,
            required:true,
            min:0
        },
        quantity:{
            type:Number,
            required:true,
            min:1
        }
    }
)
const orderSchema = new mongoose.Schema(
    {
        user:{
            type: mongoose.Schema.Types.ObjectId,
            ref:"User",
            required:true
        },
        outlet:{
            type:mongoose.Schema.Types.ObjectId,
            required:true,
            ref:"Outlet"
        },
        items:[itemSchema],
        deliveryAddress:{
            type:String,
            default:""
        },
        subTotal:{
            type:Number,
            required:true,
            min:0
        },
        deliveryFee:{
            type:Number,
            required:true,
            min:0
        },
        tax:{
            type:Number,
            min:0
        },
        discount:{
            type:Number,
            default:0,
            min:0
        },
        totalAmount:{
            type:Number,
            required:true,
            min:0
        },
        paymentMethod:{
            type:String,
            enum:["COD","UPI","CARD","NET_BANKING"],
            required:true
        },
        razorpayOrderId:{
            type:String
        },
        razorpayPaymentId:{
            type:String
        },
        paymentStatus:{
            type:String,
            enum:["pending","paid","failed","refunded"],
            default:"pending"
        },
        orderStatus:{
            type:String,
            enum:[
                "placed",
                "confirmed",
                "preparing",
                "ready",
                "out_for_delivery",
                "delivered",
                "cancelled"
            ],
            default:"placed"
        }
    },
    {
        timestamps:true
    }
)
module.exports = mongoose.model("Order",orderSchema);